/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author KIIT
 */
public class CustomerCheckin extends javax.swing.JFrame {
    Connection con=null;
    Statement st=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form CustomerCheckin
     */
    public CustomerCheckin() {
        initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","AD041002@#ad");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
        Code();
    }
    public void Code()
    {
        try
        {
            pst=con.prepareStatement("select RoomNumber from room where Bed=? and RoomType=? and Status=?");
            pst.setString(1, combobedtype.getItemAt(combobedtype.getSelectedIndex()));
            pst.setString(2,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
            pst.setString(3,"NOT-BOOKED");
            rs=pst.executeQuery();
            comboroomnumber.removeAllItems();
            while(rs.next())
            {
                comboroomnumber.addItem(rs.getString("RoomNumber"));
            }
            pst=con.prepareStatement("select Price from room where RoomNumber=?");
            pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
            rs=pst.executeQuery();
            if(rs.next())
            {
                txtprice.setText(rs.getString("Price"));
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combogender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnationality = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtaadhar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combobedtype = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboroomtype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        buttoncheckin = new javax.swing.JButton();
        buttonclear = new javax.swing.JButton();
        comboroomnumber = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 0, 91, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\KIIT\\OneDrive\\Documents\\NetBeansProjects\\Hotel Management\\Images\\checkin.png")); // NOI18N
        jLabel1.setText("CUSTOMER CHECKIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, 330, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 91, 84, 35));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 132, 313, 48));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MOBILE NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 207, -1, -1));

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 241, 313, 43));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 312, 92, 34));

        combogender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 352, 313, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NATIONALITY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 430, 189, 31));

        txtnationality.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 467, 313, 37));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AADHAR NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 544, 189, 41));

        txtaadhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 591, 313, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHECK-IN DATE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 97, 204, -1));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 136, 290, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BED TYPE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 207, 204, -1));

        combobedtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SINGLE-BED", "DOUBLE-BED" }));
        combobedtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobedtypeItemStateChanged(evt);
            }
        });
        getContentPane().add(combobedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 241, 290, 52));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ROOM TYPE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 318, 204, -1));

        comboroomtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC" }));
        comboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomtypeItemStateChanged(evt);
            }
        });
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 352, 300, 41));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ROOM NUMBER");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 204, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRICE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 204, 32));

        txtprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 591, 300, 40));

        buttoncheckin.setBackground(new java.awt.Color(153, 153, 153));
        buttoncheckin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttoncheckin.setText("CHECKIN NOW");
        buttoncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(buttoncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 637, -1, -1));

        buttonclear.setBackground(new java.awt.Color(153, 153, 153));
        buttonclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonclear.setText("CLEAR");
        buttonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonclearActionPerformed(evt);
            }
        });
        getContentPane().add(buttonclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 637, -1, -1));

        comboroomnumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(comboroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 472, 290, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\KIIT\\OneDrive\\Documents\\NetBeansProjects\\Hotel Management\\Images\\checkin-checkout.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1010, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combobedtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobedtypeItemStateChanged
        Code();
    }//GEN-LAST:event_combobedtypeItemStateChanged

    private void comboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomtypeItemStateChanged
        Code();
    }//GEN-LAST:event_comboroomtypeItemStateChanged

    private void buttonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonclearActionPerformed
        txtname.setText("");
        txtaadhar.setText("");
        txtmobile.setText("");
        txtnationality.setText("");
    }//GEN-LAST:event_buttonclearActionPerformed

    private void buttoncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncheckinActionPerformed
       if(txtname.getText().equals(""))
       {
           txtname.requestFocus();
           JOptionPane.showMessageDialog(this,"All fields are mandatory.");
       }
       else if(txtmobile.getText().equals(""))
       {
           txtmobile.requestFocus();
           JOptionPane.showMessageDialog(this,"All fields are mandatory.");
       }
       else if(txtaadhar.getText().equals(""))
       {
           txtaadhar.requestFocus();
           JOptionPane.showMessageDialog(this,"All fields are mandatory.");
       }
       else if(txtnationality.getText().equals(""))
       {
           txtnationality.requestFocus();
           JOptionPane.showMessageDialog(this,"All fields are mandatory.");
       }
       else
       {
           try {
               pst=con.prepareStatement("insert into customer(Name,Mobile,Gender,ID,Nationality,JoinDate,RoomNumber,Bed,RoomType,Price,Status)values(?,?,?,?,?,?,?,?,?,?,?)");
               pst.setString(1,txtname.getText());
               pst.setString(2,txtmobile.getText());
               pst.setString(3,combogender.getItemAt(combogender.getSelectedIndex()));
               pst.setString(4,txtaadhar.getText());
               pst.setString(5,txtnationality.getText());
               pst.setString(6,txtdate.getText());
               pst.setString(7,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
               pst.setString(8,combobedtype.getItemAt(combobedtype.getSelectedIndex()));
               pst.setString(9,comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
               pst.setString(10,txtprice.getText());
               pst.setString(11,"NULL");
               pst.executeUpdate();
               JOptionPane.showMessageDialog(this,"Customer CheckedIn Successfully.");
               txtname.setText("");
               txtaadhar.setText("");
               txtmobile.setText("");
               txtnationality.setText("");
               pst=con.prepareStatement("update room set Status=? where RoomNumber=?");
               pst.setString(1,"BOOKED");
               pst.setString(2,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
               pst.executeUpdate();
               Code();
           } catch (SQLException ex) {
               Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_buttoncheckinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncheckin;
    private javax.swing.JButton buttonclear;
    private javax.swing.JComboBox<String> combobedtype;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JComboBox<String> comboroomnumber;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtaadhar;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnationality;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
